let ramuAmount = 2000;
console.log("ramu's Amount:", ramuAmount);
let somuAmount = 3000;
console.log("somu's Amount:", somuAmount);
let totalAmount = ramuAmount + somuAmount;
console.log("total Amount:", totalAmount);
let a = 10;
let b = 20;
let sum = a + b;
console.log("sum", sum);
let difference = a - b;
console.log("difference", difference);
let product = a * b;
console.log("product", product);
let division = b / a;
console.log("division", division);

let name = "Yamini";
let role = "Developer";
console.log(`${name} is a ${role}.`);
let taskStatus = "pending";
taskStatus = "completed";
console.log("Task Status:", taskStatus);
